###################
# first_job_dagman
###################
executable = job.sh
arguments = $(Seconds)
log = job.log
output = job.$(Cluster).out
error = job.$(Cluster).err
request_cpus = 1
request_memory = 100MB
request_disk = 1GB

# HAS_CVMFS_icecube_opensciencegrid_org is an important requirement to ensure
# IceCube software is accessible from the grid compute node.
Requirements = HAS_CVMFS_icecube_opensciencegrid_org

queue
